drop table if exists JD_features;
create table JD_features(
    일련번호 not null,
    파일명 not null,
    법인명 not null,
    팀명 not null,
    직군 not null,
    직렬 not null,
    직무 not null,
    직무소개 not null,
    학위 not null,
    전공 not null,
    최소연차 not null,
    경력연차 not null,
    경력배경 not null,
    자격증 not null,
    포트폴리오 not null,
    주요업무책임 not null,
    주요업무환경 not null,
    필수자격 not null,
    필수자격요건 not null,
    선호자격요건 not null,
    필요역량 not null
    );

drop table if exists feedback;
create table feedback(
    작성자 string not null,
    이메일 string not null,
    직무 string not null,
    직무소개 string not null,
    주요업무책임 string not null,
    주요업무환경여부 string not null,
    주요업무환경 string not null,
    학위 string not null,
    주요전공 string not null,
    우대전공 string not null,
    전공 string not null,
    최소연차 string not null,
    경력연차 string not null,
    경력배경 string not null,
    경력 string not null,
    필수자격 string not null,
    선호자격요건 string not null,
    필요역량 string not null,
    자격증 string not null,
    포트폴리오 string not null,
    생성일 string not null,
    수정일 string not null,
    진행상황 string not null);